### ISSUE TITLE
请问不支持AutoModel加载吗

### ISSUE THREAD

**Issue by eyuansu62** [GAIR-NLP/auto-j#8]

**Comment by lockon-n** [comment]
支持AutoModel加载的。

![image](https://github.com/GAIR-NLP/auto-j/assets/45759388/37f5f1f3-9e28-43d2-902a-817ca9184009)

如果加载失败，请提供更多报错信息以便排查可能的错误。

**Comment by eyuansu62** [comment]
多谢，请问如果我想微调的话，需要用vllm嘛还是直接sft就行了，因为我看到论文中的关于ghost attention的部分，不太确定这部分是怎么处理的

**Comment by lockon-n** [comment]
我们的微调就是标准sft，vllm是推理时使用的加速框架，ghost att是一种数据处理技术，并不是对模型的架构进行了处理。简单来说，直接使用我们已处理好的数据进行标准sft即可。

**Comment by slchenchn** [comment]
请问有人遇到AutoModel无法加载autoj-bilingual-6b吗
代码如下：
```python
from transformers import AutoModel, AutoTokenizer


root = "/home/xxx/transformers_models/autoj-bilingual-6b"

tokenizer = AutoTokenizer.from_pretrained(root)
model = AutoModel.from_pretrained(root)

print('all done')
```

报错如下：

> Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:07<00:00,  3.90s/it]
Traceback (most recent call last):
  File "/home/xxx/code/analysis/for-verify.py", line 7, in <module>
    model = AutoModel.from_pretrained(root)
  File "/home/xxx/anaconda3/envs/llm_kb_qa3/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 467, in from_pretrained
    return model_class.from_pretrained(
  File "/home/xxx/anaconda3/envs/llm_kb_qa3/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2777, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/home/xxx/anaconda3/envs/llm_kb_qa3/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3168, in _load_pretrained_model
    raise RuntimeError(f"Error(s) in loading state_dict for {model.__class__.__name__}:\n\t{error_msg}")
RuntimeError: Error(s) in loading state_dict for LlamaModel:
        size mismatch for model.layers.0.self_attn.k_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.0.self_attn.v_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.1.self_attn.k_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.1.self_attn.v_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.2.self_attn.k_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.2.self_attn.v_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.3.self_attn.k_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.3.self_attn.v_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.4.self_attn.k_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.4.self_attn.v_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.5.self_attn.k_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.5.self_attn.v_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.6.self_attn.k_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.6.self_attn.v_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.7.self_attn.k_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.7.self_attn.v_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.8.self_attn.k_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.8.self_attn.v_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.9.self_attn.k_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.9.self_attn.v_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.10.self_attn.k_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.10.self_attn.v_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.11.self_attn.k_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.11.self_attn.v_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.12.self_attn.k_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.12.self_attn.v_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.13.self_attn.k_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.13.self_attn.v_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.14.self_attn.k_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.14.self_attn.v_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.15.self_attn.k_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.15.self_attn.v_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.16.self_attn.k_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.16.self_attn.v_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.17.self_attn.k_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.17.self_attn.v_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.18.self_attn.k_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.18.self_attn.v_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.19.self_attn.k_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.19.self_attn.v_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.20.self_attn.k_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.20.self_attn.v_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.21.self_attn.k_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.21.self_attn.v_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.22.self_attn.k_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.22.self_attn.v_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.23.self_attn.k_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.23.self_attn.v_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.24.self_attn.k_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.24.self_attn.v_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.25.self_attn.k_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.25.self_attn.v_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.26.self_attn.k_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.26.self_attn.v_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.27.self_attn.k_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.27.self_attn.v_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.28.self_attn.k_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.28.self_attn.v_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.29.self_attn.k_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.29.self_attn.v_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.30.self_attn.k_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.30.self_attn.v_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.31.self_attn.k_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        size mismatch for model.layers.31.self_attn.v_proj.weight: copying a param with shape torch.Size([512, 4096]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
        You may consider adding `ignore_mismatched_sizes=True` in the model `from_pretrained` method.

**Comment by StarWalkin** [comment]
您好 @slchenchn ，我们尝试运行你提供的代码来加载autoj-bilingual-6b，并没有遇到问题，如下图
<img width="1547" alt="image" src="https://github.com/GAIR-NLP/auto-j/assets/135338285/1445bde2-9094-4534-9bce-87c10ed57239">
您可以提供您环境中transformers库的版本号等信息以便进一步排查问题

**Comment by slchenchn** [comment]
我更新了transformers发现就可以正常运行了，感谢！
